In [1]:
from datasets import load_dataset, Dataset, DatasetDict
import pandas as pd
import torch
import transformers
import os
import argparse
from transformers import AutoModelForCausalLM, AutoTokenizer, set_seed, Trainer, TrainingArguments, BitsAndBytesConfig, \
    DataCollatorForLanguageModeling, Trainer, TrainingArguments, BloomForCausalLM, BloomTokenizerFast, pipeline, \
    EarlyStoppingCallback
from huggingface_hub.hf_api import HfFolder

/home/minhnh/python_venv/nlp/lib/python3.9/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
2024-05-17 03:57:43.688079: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2024-05-17 03:57:44.692521: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT

In [4]:
from sklearn.feature_extraction.text import TfidfVectorizer
tfidf_vect = TfidfVectorizer()

In [5]:
HF_TOKEN = {
    "TeeA": "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",
    "hoangphu7122002ai": "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"
}
WANDB_KEY = {
    "TeeA": "b00b6b93ecaa8ede6811c93254f59f821c7632ca"
}

In [14]:
from huggingface_hub.hf_api import HfFolder

HfFolder.save_token('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')
dataset = load_dataset("ikura31/section_TVPL")

Downloading data: 100%|██████████| 3.86G/3.86G [02:57<00:00, 21.8MB/s]
Generating train split: 9936033 examples [01:13, 134536.25 examples/s]

In [20]:
dataset['train'][3]

{'_id': '72454f4cb4edfcd7453258cf49f88155',
 'category': 'Bo-may-hanh-chinh',
 'link': 'https://thuvienphapluat.vn/van-ban/Bo-may-hanh-chinh/Nghi-quyet-94-NQ-HDND-2017-Chuong-trinh-giam-sat-cua-Hoi-dong-tinh-Ha-Giang-356885.aspx',
 'loai_van_ban': 'Nghị quyết',
 'section': '<section>',
 'is_section': True,
 'section_content': ' Căn cứ Luật Tổ chức chính quyền địa phương ngày 19 tháng 6 năm 2015;',
 'content': None}

In [21]:
df_pandas = dataset['train'].to_pandas()

In [22]:
df_pandas.head()

,_id,category,link,loai_van_ban,section,is_section,section_content,content
0,72454f4cb4edfcd7453258cf49f88155,Bo-may-hanh-chinh,https://thuvienphapluat.vn/van-ban/Bo-may-hanh...,Nghị quyết,<section>,True,NGHỊ QUYẾT,None
1,72454f4cb4edfcd7453258cf49f88155,Bo-may-hanh-chinh,https://thuvienphapluat.vn/van-ban/Bo-may-hanh...,Nghị quyết,<section>,True,BAN HÀNH CHƯƠNG TRÌNH GIÁM SÁT NĂM 2018 CỦA H...,None
2,72454f4cb4edfcd7453258cf49f88155,Bo-may-hanh-chinh,https://thuvienphapluat.vn/van-ban/Bo-may-hanh...,Nghị quyết,<section>,True,HỘI ĐỒNG NHÂN DÂN TỈNH HÀ GIANG KHÓA XVII - K...,None
3,72454f4cb4edfcd7453258cf49f88155,Bo-may-hanh-chinh,https://thuvienphapluat.vn/van-ban/Bo-may-hanh...,Nghị quyết,<section>,True,Căn cứ Luật Tổ chức chính quyền địa phương ng...,None
4,72454f4cb4edfcd7453258cf49f88155,Bo-may-hanh-chinh,https://thuvienphapluat.vn/van-ban/Bo-may-hanh...,Nghị quyết,<section>,True,Căn cứ Luật Hoạt động giám sát của Quốc hội v...,None

In [23]:
import json
import re

import pandas
import regex
# from bs4 import BeautifulSoup

pandas.options.mode.chained_assignment = None


class SectionAnalyzer:
    def __init__(self):
        pass

    def starts_with_keyword(self, input_str: str, replace: bool = False):
        """
        Check if the input string starts with specific keywords or patterns.

        Parameters:
        input_str (str): The input string to be checked.
        replace (bool, optional): If True, replace the keyword with an empty string or return the remaining string after the keyword. Defaults to False.

        Returns:
        bool or str: If `replace` is False, returns True if the input string starts with a keyword or pattern, False otherwise.
                    If `replace` is True, returns the modified string after replacing the keyword with an empty string, or returns the remaining string after the keyword.
        """

        # Keywords to check for at the beginning of the input string
        keywords = ["<i>", "<section>"]

        for keyword in keywords:
            if input_str.startswith(keyword):
                if replace:
                    return input_str.replace(keyword, '')
                return True

        # if self.is_all_uppercase(input_str):
        #     if replace:
        #         return input_str
        #     return True

        # Check if the input string starts with 'Điều', 'Chương', 'Phần', 'Mục'
        # followed by a number or a Roman numeral
        pattern = r"^(Điều|Chương|Phần|Mục)\s+(.*)$"
        match = re.match(pattern, input_str)
        if match:
            try:
                # Extract the next word after the keyword
                next_word = input_str.split(' ')[1]
                # Remove punctuation marks from the next word
                next_word = re.sub(r'[.,()]+', '', next_word)
                if self.is_number(next_word) and replace:
                    # If replace is True, return the string after removing the keyword and the number
                    return ' '.join(input_str.split()[2:])
                return self.is_number(next_word)  # Return True if the next word is a number or a Roman numeral
            except:
                print("Có ký tự không mong muốn")

        else:
            if replace:
                return input_str
            return False

    @staticmethod
    def starts_with_number_alphabet(input_str: str, replace: bool = False):
        """
        Check if the input string starts with a number, a Roman numeral, or an alphabet character.

        Parameters:
        input_str (str): The input string to be checked.
        replace (bool, optional): If True, returns the remaining string after the initial number, Roman numeral,
                                  or alphabet character. Defaults to False.

        Returns:
        bool or str: If `replace` is False, returns True if the input string starts with a number, a Roman numeral,
                     or an alphabet character, False otherwise.
                     If `replace` is True, returns the modified string after removing the initial number, Roman numeral,
                     or alphabet character.
        """

        # Regular expression pattern to match numbers, Roman numerals, or alphabet characters at the beginning of the
        # input string
        pattern = r'^([0-9]+|^M{0,3}(CM|CD|D?C{0,3})?(XC|XL|L?X{0,3})?(IX|IV|V?I{0,3})?+|[a-zA-ZàáãạảăắằẳẵặâấầẩẫậèéẹẻẽêềếểễệđìíĩỉịòóõọỏôốồổỗộơớờởỡợùúũụủưứừửữựỳỵỷỹýÀÁÃẠẢĂẮẰẲẴẶÂẤẦẨẪẬÈÉẸẺẼÊỀẾỂỄỆĐÌÍĨỈỊÒÓÕỌỎÔỐỒỔỖỘƠỚỜỞỠỢÙÚŨỤỦƯỨỪỬỮỰỲỴỶỸÝ])([.)])'

        # Check if the input string matches the pattern
        check = bool(re.match(pattern, input_str))

        if replace:
            if check:
                # If the input string matches the pattern and replace is True, return the string after the initial
                # character
                return ' '.join(input_str.split()[1:])
            else:
                return input_str  # Return the input string unchanged if it does not match the pattern
        else:
            return check  # Return True if the input string matches the pattern, False otherwise

    @staticmethod
    def is_number(num: str):
        """
        Determine whether the input is a valid number or a Roman numeral.

        Parameters:
        num (str): The input string to be checked.

        Returns:
        bool: True if the input is a valid number or a Roman numeral, False otherwise.
        """

        # Regular expression pattern for Roman numerals
        roman = re.compile(r"""^M{0,3}(CM|CD|D?C{0,3})?(XC|XL|L?X{0,3})?(IX|IV|V?I{0,3})?$""", re.VERBOSE)

        # Regular expression pattern for numbers
        number = re.compile(r'^([\s\d]+)$')

        # Check if the input matches either the Roman numeral pattern or the number pattern
        if re.match(roman, num) or re.match(number, num):
            return True
        return False

    @staticmethod
    def is_all_uppercase(input_str: str):
        """
        Check if all characters in the input string are uppercase.

        Parameters:
        input_string (str): The input string to be checked.

        Returns:
        bool: True if all characters in the input string are uppercase, False otherwise.
        """
        return input_str.isupper()

    def check_replace_section(self, input_str: str, replace: bool = False):
        """
        Check if the input string starts with a specific keyword, a number, a Roman numeral, or is all uppercase.
        Optionally, replace the starting keyword or characters with an empty string.

        Parameters: input_str (str): The input string to be checked. replace (bool, optional): If True, replaces the
        starting keyword or characters with an empty string. Defaults to False.

        Returns: bool or str:
        If `replace` is False, returns True if the input string starts with a keyword, a number, a Roman numeral,
        or is all uppercase. False otherwise.
        If `replace` is True, returns the modified string after removing the starting keyword or characters.
        """
        if replace:
            if self.starts_with_keyword(input_str):
                return self.starts_with_keyword(input_str, replace)
            if self.starts_with_number_alphabet(input_str):
                return self.starts_with_number_alphabet(input_str, replace)
            return input_str
        else:
            return self.starts_with_keyword(input_str) or self.starts_with_number_alphabet(
                input_str) or self.is_all_uppercase(
                input_str)

    # @staticmethod
    # def get_text(html_doc: str):
    #     """
    #     Extract text content from HTML document.

    #     Parameters:
    #     html_doc (str): The HTML document to extract text from.

    #     Returns:
    #     list: A list containing the extracted text content. Each element represents a paragraph or section of text.
    #     """

    #     # Add a marker to the end of the HTML document to indicate the end of content
    #     end_mark = '''<p align="center"><b>END</b></p>'''
    #     html_doc = html_doc + end_mark

    #     # Create a BeautifulSoup object from the HTML
    #     soup = BeautifulSoup(html_doc, 'html.parser')

    #     # Find all <p> tags
    #     paragraphs = soup.find_all('p')

    #     # Find the index of the first <p align="center"> tag
    #     start_index = -1
    #     for i, p in enumerate(paragraphs):
    #         if p.get('align') == 'center':
    #             start_index = i
    #             break

    #     # Get the content of the first <p align="center"> tag
    #     first_centered_paragraph_text = []
    #     if start_index != -1:
    #         first_centered_paragraph_text.append(paragraphs[start_index].text.replace('\xa0', ' '))

    #     # Find the index of the last <p align="center"> tag
    #     end_index = -1
    #     for i, p in enumerate(paragraphs[::-1]):
    #         if p.get('align') == 'center':
    #             end_index = len(paragraphs) - 1 - i
    #             break

    #     # Get the text content of paragraphs between the first and last <p align="center"> tags
    #     middle_paragraphs_text = []
    #     if start_index != -1 and end_index != -1:
    #         middle_paragraphs = paragraphs[start_index + 1:end_index]
    #         for p in middle_paragraphs:
    #             if p.get('align') == 'center':
    #                 middle_paragraphs_text.append("<section> " + p.text)
    #             elif p.i and p.i == p.contents[0]:
    #                 middle_paragraphs_text.append("<section> " + p.text)
    #             else:
    #                 middle_paragraphs_text.append(p.text)

    #     # Combine the content of the first <p align="center"> tag and paragraphs between align="center" tags
    #     result = first_centered_paragraph_text + middle_paragraphs_text
    #     result[0] = "<section> " + result[0]

    #     return result

    @staticmethod
    def replace_table(noi_dung_html, danh_sach_bang):
        """
        Replace HTML tables with custom tags representing JSON tables.

        Parameters:
        noi_dung_html (str): The HTML content containing tables to be replaced.
        danh_sach_bang (str): A JSON string containing table data.

        Returns:
        str: The modified HTML content with tables replaced by custom tags.
        """

        danh_sach_bang = json.loads(danh_sach_bang)

        for name, df in danh_sach_bang.items():
            # Replace each table in the HTML content with a custom tag representing the table
            noi_dung_html = regex.sub(r"<table[^>]*>(.|\n)*?</table>",
                                      f'<p> &lt;jsontable name="{name}"&gt; &lt;/jsontable&gt;</p>',
                                      noi_dung_html,
                                      count=1)

        return noi_dung_html

    def upper_section(self, input_str):
        if self.is_all_uppercase(input_str):
            return '<section> ' + input_str

        else:
            return input_str

    def section_processing(self, df: pandas.DataFrame, infer=False):
        """
        Process DataFrame containing HTML content and table data to extract sections and content.

        Parameters:
        df (pandas.DataFrame): DataFrame containing columns '_id', 'category', 'link', 'loai_van_ban', 'noi_dung_html', and 'danh_sach_bang'.

        Returns:
        pandas.DataFrame: Processed DataFrame with additional columns 'section', 'is_section', 'section_content', and 'content'.
        """

        # Select required columns from the DataFrame
        if not infer:
            try:
                df = df[['_id', 'category', 'link', 'loai_van_ban', 'noi_dung_html', 'danh_sach_bang']]
            except KeyError as e:
                # Handle the exception, print an error message, or take any necessary actions
                print("KeyError occurred:", e)

            # Convert 'danh_sach_bang' column from bytes to string
            df.loc[:, 'danh_sach_bang'] = df['danh_sach_bang'].apply(lambda x: x.decode('utf-8'))

            # Replace tables in HTML content with custom tags
            df['noi_dung_html'] = df.apply(lambda row: self.replace_table(row['noi_dung_html'], row['danh_sach_bang']),
                                           axis=1)

            # Extract sections from HTML content
            df['section'] = df['noi_dung_html'].apply(lambda x: self.get_text(html_doc=x))

            # Drop unnecessary columns
            df = df.drop(['noi_dung_html', 'danh_sach_bang'], axis=1)

            # Explode DataFrame on 'section' column
            df = df.explode('section')

        # Remove unwanted characters and extra spaces from sections
        df['section'] = df['section'].apply(lambda x: x.replace('\xa0', ' '))
        df['section'] = df['section'].apply(lambda x: x.replace('\r\n', ' '))
        df['section'] = df['section'].apply(lambda x: x.replace('\n', ' '))
        df['section'] = df['section'].apply(lambda x: x.strip())
        df['section'] = df['section'].apply(lambda x: re.sub(r'\s+', ' ', x))

        # Drop rows with null values in 'section' column
        df.dropna(subset=['section'], inplace=True)

        # Check if each section is a section or content
        df['is_section'] = df['section'].apply(lambda x: self.check_replace_section(x))

        section_list = df['section'].to_list()
        is_section_list = df['is_section'].to_list()

        if infer:
            str_add = ''
            new_section_list = []
            new_is_section_list = []
            for i in range(len(section_list)):
                if not is_section_list[i]:
                    str_add += section_list[i].replace('\n', '') + ' '
                else:
                    if str_add != '':
                        new_section_list.append(str_add)
                        new_is_section_list.append(False)
                        str_add = ''
                    new_section_list.append(section_list[i].replace('\n', ''))
                    new_is_section_list.append(True)

            if str_add != '':
                new_section_list.append(str_add)
                new_is_section_list.append(False)

            df = pandas.DataFrame({
                'section': new_section_list,
                'is_section': new_is_section_list
            })
            df['section'] = df['section'].apply(lambda x: self.upper_section(x))

        # Extract section content and remove it from section column
        df['section_content'] = df['section'].apply(lambda x: self.check_replace_section(x, True))
        df['section_content'] = df.apply(lambda row: row['section_content'] if row['is_section'] else '', axis=1)

        # Create 'content' column containing non-section text
        df['content'] = df.apply(lambda row: row['section'] if not row['is_section'] else '', axis=1)

        # Remove section content from section column
        df['section'] = df.apply(lambda row: row['section'].replace(row['section_content'], ''), axis=1)

        # Remove content from section column
        df['section'] = df.apply(lambda row: row['section'] if row['is_section'] else '', axis=1)

        # Reset index of DataFrame
        df = df.reset_index(drop=True)

        return df

In [24]:
import re

import pandas


class SectionClassifier:
    def __init__(self):
        pass

    @staticmethod
    def is_roman(input_str):
        roman = r'^M{0,3}(CM|CD|D?C{0,3})?(XC|XL|L?X{0,3})?(IX|IV|V?I{0,3})?([.)])'
        return bool(re.match(roman, input_str))

    @staticmethod
    def is_number(input_str):
        number = r'^([\s\d]+)([.):])'
        return bool(re.match(number, input_str))

    @staticmethod
    def get_number(input_str):
        try:
            next_word = input_str.split(' ')[1]
            # next_word = re.sub(r'[.,()]+', '', next_word)
            return next_word
        except:
            return None

    @staticmethod
    def starts_with_number_alphabet(input_str, replace=False):
        pattern = r'^([0-9]+|^M{0,3}(CM|CD|D?C{0,3})?(XC|XL|L?X{0,3})?(IX|IV|V?I{0,3})?+|[a-zA-ZàáãạảăắằẳẵặâấầẩẫậèéẹẻẽêềếểễệđìíĩỉịòóõọỏôốồổỗộơớờởỡợùúũụủưứừửữựỳỵỷỹýÀÁÃẠẢĂẮẰẲẴẶÂẤẦẨẪẬÈÉẸẺẼÊỀẾỂỄỆĐÌÍĨỈỊÒÓÕỌỎÔỐỒỔỖỘƠỚỜỞỠỢÙÚŨỤỦƯỨỪỬỮỰỲỴỶỸÝ])([.)])'
        check = bool(re.match(pattern, input_str))
        if replace:
            if check:
                return ' '.join(input_str.split()[1:])
            else:
                return input_str
        else:
            return check

    @staticmethod
    def is_all_uppercase(input_str: str):
        """
        Check if all characters in the input string are uppercase.

        Parameters:
        input_string (str): The input string to be checked.

        Returns:
        bool: True if all characters in the input string are uppercase, False otherwise.
        """
        return input_str.isupper()

    def classify(self, input_str):
        input_str = str(input_str)

        keywords = ["<i>", "<section>"]
        for keyword in keywords:
            if input_str.startswith(keyword):
                return '0'

        pattern_1 = r"^(Điều)\s+(.*)$"
        pattern_2 = r"^(Chương)\s+(.*)$"
        pattern_3 = r"^(Phần)\s+(.*)$"
        pattern_4 = r"^(Mục)\s+(.*)$"

        number = self.get_number(input_str)
        # Điều
        if re.match(pattern_1, input_str):
            if self.is_number(number):
                return '1'
            if self.is_roman(number):
                return '2'
        # Chương
        if re.match(pattern_2, input_str):
            input_str = input_str + '.'
            if self.is_number(number):
                return '3'
            if self.is_roman(number):
                return '4'
        # Phần
        if re.match(pattern_3, input_str):
            input_str = input_str + '.'
            if self.is_number(number):
                return '5'
            if self.is_roman(number):
                return '6'
        # Mục
        if re.match(pattern_4, input_str):
            input_str = input_str + '.'
            if self.is_number(number):
                return '7'
            if self.is_roman(number):
                return '8'

        if self.is_number(input_str):
            return '9'

        if self.is_roman(input_str):
            return '10'

        if not self.is_all_uppercase(input_str):
            return '11'

        if self.is_all_uppercase(input_str):
            return '12'

        if input_str == 'nan':
            return '-1'

    @staticmethod
    def calculate_len(row):
        if row['is_section']:
            return len((str(row['section']) + str(row['section_content'])).split(' '))
        else:
            return len(str(row['content']).split(' '))

    def section_classifier(self, df: pandas.DataFrame, infer=False):
        df['section'] = df['section'].apply(lambda x: str(x).strip())
        df['class'] = df['section'].apply(lambda x: self.classify(x))
        if not infer:
            rm_list = list(df[df['class'].isna()].groupby(['_id'])['_id'].value_counts().index)
            df = df[~df['_id'].isin(rm_list)]
        df['len'] = df.apply(lambda x: self.calculate_len(x), axis=1)
        return df


class SectionMerger:
    def __init__(self):
        pass

    @staticmethod
    def refine_idx_group(idx_group):
        list_idx = [(idx_group[0][0], 0)]
        run = 0
        for i in range(1, len(idx_group)):
            if idx_group[i][1] != idx_group[i - 1][1]:
                run += 1
            list_idx.append((idx_group[i][0], run))
        return list_idx

    def gen_idx_merge(self, df, max_len=1000):
        # max_len = 1000
        count = 0
        list_df = []

        ele = df
        section = ele['class'].to_list()
        len_data = ele['len'].to_list()

        idx_group = []

        stack = []
        run = 0
        count_right = 0
        len_sum = 0
        for i in range(len(len_data)):
            if count_right != 0:
                count_right -= 1
                continue

            if len(stack) == 0:
                if len_sum + len_data[i] > max_len:
                    idx_group.append((i, run))
                    run += 1
                    len_sum = 0
                else:
                    stack.append((section[i], len_data[i], i, len_data[i]))
            elif section[i] != stack[-1][0]:
                if len_sum + stack[-1][1] + len_data[i] > max_len:

                    while len(stack) != 0:
                        _, _, j, len_val = stack.pop()
                        len_sum += len_val
                        if len_sum > max_len:
                            len_sum = len_val
                            run += 1
                        idx_group.append((j, run))
                    len_sum = 0
                    run += 1
                    stack.append((section[i], len_data[i], i, len_data[i]))
                else:
                    stack.append((section[i], len_data[i] + stack[-1][1], i, len_data[i]))
            else:
                if stack[-1][1] + len_data[i] <= max_len:
                    stack.append((section[i], stack[-1][1] + len_data[i], i, len_data[i]))

                else:

                    stack_i_run = []
                    while len(stack) != 0 and stack[-1][0] == section[i]:
                        stack_i_run.append(stack.pop())
                    count_left = len(stack_i_run)
                    # stack_i_run = list(reversed(stack_i_run))

                    count_right = 0
                    stack_i_run.append((section[i], len_data[i], i, len_data[i]))
                    for i_run in range(i + 1, len(len_data)):
                        if section[i_run] == section[i]:
                            stack_i_run.append((section[i_run], len_data[i_run], i_run, len_data[i_run]))
                            count_right += 1
                        else:
                            break

                    len_sum = 0

                    while len(stack) != 0:
                        _, _, j, len_val = stack.pop()
                        len_sum += len_val
                        if len_sum > max_len:
                            len_sum = len_val
                            run += 1
                        idx_group.append((j, run))
                    run += 1
                    len_sum = 0
                    # stack_i_run = list(reversed(stack_i_run))
                    while len(stack_i_run) != 0:
                        _, _, j, len_val = stack_i_run.pop()
                        len_sum += len_val
                        if len_sum > max_len:
                            len_sum = len_val
                            run += 1
                        idx_group.append((j, run))

        len_sum = 0

        while len(stack) != 0:
            _, _, j, len_val = stack.pop()
            len_sum += len_val
            if len_sum > max_len:
                len_sum = len_val
                run += 1
            idx_group.append((j, run))

        idx_group.sort(key=lambda x: x[0])

        idx_group = self.refine_idx_group(idx_group)

        check_set = set()
        for ele_ in idx_group:
            if len_data[ele_[0]] != 0:
                check_set.add(ele_[1])
        count += len(check_set)
        ele['idx_merge'] = [ele_[1] for ele_ in idx_group]
        list_df.append(ele)
        return pandas.concat(list_df, ignore_index=True)

    def gen_idx_merge_2(self, df, max_len=1000):
        # max_len = 1000
        count = 0
        list_df = []

        ele = df
        section = ele['class'].to_list()
        len_data = ele['len'].to_list()

        idx_group = []

        stack = []
        run = 0
        count_right = 0
        len_sum = 0
        for i in range(len(len_data)):
            if count_right != 0:
                count_right -= 1
                continue

            if len(stack) == 0:
                if len_sum + len_data[i] > max_len:
                    idx_group.append((i, run))
                    run += 1
                    len_sum = 0
                else:
                    stack.append((section[i], len_data[i], i, len_data[i]))
                    len_sum += len_data[i]
            elif section[i] != stack[-1][0]:
                if len_sum + stack[-1][1] + len_data[i] > max_len:

                    while len(stack) != 0:
                        _, _, j, len_val = stack.pop()
                        len_sum += len_val
                        if len_sum > max_len:
                            len_sum = 0
                            idx_group.append((j, run))
                            run += 1
                        else:
                            idx_group.append((j, run))
                    # len_sum = 0
                    # run += 1
                    stack.append((section[i], len_data[i], i, len_data[i]))
                else:
                    stack.append((section[i], len_data[i] + stack[-1][1], i, len_data[i]))
            else:
                if len_sum + stack[-1][1] + len_data[i] <= max_len:
                    stack.append((section[i], stack[-1][1] + len_data[i], i, len_data[i]))

                else:

                    stack_i_run = []
                    while len(stack) != 0 and stack[-1][0] == section[i]:
                        stack_i_run.append(stack.pop())
                    stack_i_run = list(reversed(stack_i_run))

                    count_right = 0
                    stack_i_run.append((section[i], len_data[i], i, len_data[i]))
                    for i_run in range(i + 1, len(len_data)):
                        if section[i_run] == section[i]:
                            stack_i_run.append((section[i_run], len_data[i_run], i_run, len_data[i_run]))
                            count_right += 1
                        else:
                            break

                    # len_sum = 0

                    while len(stack) != 0:
                        _, _, j, len_val = stack.pop()
                        len_sum += len_val
                        if len_sum > max_len:
                            len_sum = 0
                            idx_group.append((j, run))
                            run += 1
                        else:
                            idx_group.append((j, run))
                    # run += 1
                    # len_sum = 0
                    stack_i_run = list(reversed(stack_i_run))
                    while len(stack_i_run) != 0:
                        _, _, j, len_val = stack_i_run.pop()
                        len_sum += len_val
                        if len_sum > max_len:
                            len_sum = 0
                            idx_group.append((j, run))
                            run += 1
                        else:
                            idx_group.append((j, run))
        # len_sum = 0

        while len(stack) != 0:
            _, _, j, len_val = stack.pop()
            len_sum += len_val
            if len_sum > max_len:
                len_sum = 0
                idx_group.append((j, run))
                run += 1
            else:
                idx_group.append((j, run))

        idx_group.sort(key=lambda x: x[0])


        idx_group = self.refine_idx_group(idx_group)

        check_set = set()
        for ele_ in idx_group:
            if len_data[ele_[0]] != 0:
                check_set.add(ele_[1])
        count += len(check_set)
        ele['idx_merge'] = [ele_[1] for ele_ in idx_group]
        list_df.append(ele)
        return pandas.concat(list_df, ignore_index=True)

    @staticmethod
    def combine_columns(row):
        # return f"\n{str(row['section']).strip()} {str(row['section_content']).strip()}{str(row['content']).strip()}"
        return f"{str(row['section']).strip()} {str(row['section_content']).strip()}{str(row['content']).strip()}"

    def section_merge(self, df: pandas.DataFrame, max_len=1000, choose = 1, infer=False):
        classifier = SectionClassifier()
        df = classifier.section_classifier(df, infer=True)
        if choose == 1:
            df = self.gen_idx_merge(df, max_len=max_len)
        else:
            df = self.gen_idx_merge_2(df, max_len=max_len)
        df = df.fillna('')
        df['section'] = df['section'].apply(lambda x: x.replace('<section>', ''))
        df['text'] = df.apply(self.combine_columns, axis=1)
        return df.groupby(['idx_merge'])['text'].apply(' '.join).reset_index()

In [25]:
classifier = SectionClassifier()

In [26]:
df = df_pandas

In [27]:
df = classifier.section_classifier(df, infer=True)
df

,_id,category,link,loai_van_ban,section,is_section,section_content,content,class,len
0,72454f4cb4edfcd7453258cf49f88155,Bo-may-hanh-chinh,https://thuvienphapluat.vn/van-ban/Bo-may-hanh...,Nghị quyết,<section>,True,NGHỊ QUYẾT,None,0,3
1,72454f4cb4edfcd7453258cf49f88155,Bo-may-hanh-chinh,https://thuvienphapluat.vn/van-ban/Bo-may-hanh...,Nghị quyết,<section>,True,BAN HÀNH CHƯƠNG TRÌNH GIÁM SÁT NĂM 2018 CỦA H...,None,0,24
2,72454f4cb4edfcd7453258cf49f88155,Bo-may-hanh-chinh,https://thuvienphapluat.vn/van-ban/Bo-may-hanh...,Nghị quyết,<section>,True,HỘI ĐỒNG NHÂN DÂN TỈNH HÀ GIANG KHÓA XVII - K...,None,0,15
3,72454f4cb4edfcd7453258cf49f88155,Bo-may-hanh-chinh,https://thuvienphapluat.vn/van-ban/Bo-may-hanh...,Nghị quyết,<section>,True,Căn cứ Luật Tổ chức chính quyền địa phương ng...,None,0,16
4,72454f4cb4edfcd7453258cf49f88155,Bo-may-hanh-chinh,https://thuvienphapluat.vn/van-ban/Bo-may-hanh...,Nghị quyết,<section>,True,Căn cứ Luật Hoạt động giám sát của Quốc hội v...,None,0,22
...,...,...,...,...,...,...,...,...,...,...
9936028,d4804b6bb947b35b5f76c99f8b4e8472,Thuong-mai,https://thuvienphapluat.vn/van-ban/Thuong-mai/...,Thông báo,None,False,None,"- Chủ trì, phối hợp với các đơn vị: Cục Quản l...",11,87
9936029,d4804b6bb947b35b5f76c99f8b4e8472,Thuong-mai,https://thuvienphapluat.vn/van-ban/Thuong-mai/...,Thông báo,None,False,None,Văn phòng Bộ thông báo để các đơn vị biết và t...,11,15
9936030,d4804b6bb947b35b5f76c99f8b4e8472,Thuong-mai,https://thuvienphapluat.vn/van-ban/Thuong-mai/...,Thông báo,None,False,None,None,11,1
9936031,d4804b6bb947b35b5f76c99f8b4e8472,Thuong-mai,https://thuvienphapluat.vn/van-ban/Thuong-mai/...,Thông báo,None,False,None,"<jsontable name=""bang_1""> </jsontable>",11,3
9936032,d4804b6bb947b35b5f76c99f8b4e8472,Thuong-mai,https://thuvienphapluat.vn/van-ban/Thuong-mai/...,Thông báo,None,False,None,None,11,1

In [28]:
merger = SectionMerger()

In [29]:
data = merger.section_merge(df, max_len=2000,choose = 2)

In [30]:
data['len'] = data['text'].apply(lambda x: len(x.split(' ')))

In [31]:
dataset = Dataset.from_pandas(data)

In [36]:
dataset = dataset.map(lambda example : {'text' : example['text'].replace('None','')})

Map: 100%|██████████| 135046/135046 [00:18<00:00, 7246.11 examples/s]

In [39]:
dataset[2]

{'idx_merge': 2,
 'text': ' - Cơ sở để xây dựng chương trình phát triển của từng đô thị, đồng thời huy động các nguồn lực để đầu tư xây dựng phát triển đô thị, đảm bảo nâng cao chất lượng, diện mạo kiến trúc cảnh quan đô thị theo hướng hiện đại, văn minh, bền vững, giữ gìn và phát huy những giá trị, bản sắc văn hóa của mỗi đô thị. III. Các chỉ tiêu về phát triển đô thị 1. Về hệ thống đô thị  - Đến năm 2020: Phấn đấu toàn Tỉnh có 23 đô thị, trong đó: 02 đô thị loại II (thành phố Cao Lãnh, thành phố Sa Đéc), 01 đô thị loại III (thị xã Hồng Ngự), 05 đô thị loại IV (thị trấn Lấp Vò, thị trấn Mỹ An, thị trấn Mỹ Thọ, thị trấn Tràm Chim, thị trấn Thanh Bình) và 15 đô thị loại V. Quy mô diện tích đất xây dựng đô thị khoảng 9.500ha, dân số đô thị khoảng 679.000 người. Tỷ lệ đô thị hóa khoảng 38%.  - Đến năm 2025: Phấn đấu toàn tỉnh có 27 đô thị, trong đó: 02 đô thị loại II (thành phố Cao Lãnh, thành phố Sa Đéc), 01 đô thị loại III (thị xã Hồng Ngự), 08 đô thị loại IV (thị trấn Lấp Vò, thị trấn Mỹ An, thị trấn Mỹ Thọ, thị trấn Tràm Chim, thị trấn Thanh Bình, thị trấn Cái Tàu Hạ - Nha Mân, thị trấn Lai Vung, thị trấn Sa Rài) và 16 đô thị loại V. Quy mô diện tích đất xây dựng đô thị khoảng 12.100ha, dân số đô thị khoảng 820.000 người. Tỷ lệ đô thị hóa khoảng 44%.  - Đến năm 2030: Phấn đấu toàn tỉnh có 32 đô thị, trong đó: 02 đô thị loại I (thành phố Cao Lãnh, thành phố Sa Đéc), 01 đô thị loại II (thị xã Hồng Ngự), 01 đô thị loại III (thị xã Mỹ An), 07 đô thị loại IV (thị trấn Lấp Vò, thị trấn Mỹ Thọ, thị trấn Tràm Chim, thị trấn Thanh Bình, thị trấn Cái Tàu Hạ - Nha Mân, thị trấn Lai Vung, thị trấn Sa Rài) và 21 đô thị loại V. Quy mô diện tích đất xây dựng đô thị khoảng 14.800ha, dân số đô thị khoảng 960.000 người. Tỷ lệ đô thị hóa khoảng 48%. 2. Về chất lượng đô thị  - Đến năm 2020:  + Diện tích sàn nhà ở đô thị bình quân đạt 23m2/người; tỷ lệ nhà kiên cố toàn tỉnh đạt khoảng 65%.  + Tỷ lệ giao thông so với diện tích đất xây dựng đô thị từ 15% trở lên. Tỷ lệ vận tải hành khách công cộng đáp ứng nhu cầu tại đô thị từ loại IV trở lên đạt từ 10 - 15%; các đô thị loại V đạt từ 2 - 5%.  + Tỷ lệ dân cư đô thị được cấp nước sạch tại các đô thị đạt 97%; tiêu chuẩn cấp nước cho đô thị từ loại IV trở lên đạt 120 lít/người/ngày đêm, đô thị loại V đạt 100 lít/người/ngày đêm.  + Tỷ lệ bao phủ của hệ thống thoát nước đạt 85% diện tích lưu vực thoát nước trong các đô thị và 60% lượng nước thải sinh hoạt được thu gom và xử lý; 100% các cơ sở sản xuất mới áp dụng công nghệ sạch hoặc trang bị các thiết bị giảm ô nhiễm. Các cơ sở gây ô nhiễm môi trường nghiêm trọng được xử lý đạt 95%.  + Tỷ lệ chất thải rắn sinh hoạt thu gom và xử lý đạt 80% tổng lượng chất thải rắn sinh hoạt đô thị; đạt 95% chắt thải rắn khu công nghiệp, chất thải rắn y tế nguy hại được thu gom và xử lý đảm bảo tiêu chuẩn môi trường.  + Tỷ lệ chiều dài các tuyến đường chính và khu nhà ở, ngõ xóm được chiếu sáng tại các đô thị loại II đạt tỷ lệ 90%. Từng bước phát triển đồng bộ chiếu sáng đối với đô thị loại III, loại IV, loại V đạt 85% chiều dài các tuyến đường chính và đạt 80% chiều dài đường khu nhà ở, ngõ xóm.  + Đất cây xanh đô thị, đối với đô thị loại II, loại III đạt 7m2/người, đô thị loại IV, loại V đạt 5m2/người. Đất cây xanh công cộng khu vực nội thị của các đô thị từ loại II đến đô thị loại V đạt 3 - 5m2/người.  - Đến năm 2025:  + Diện tích sàn nhà ở đô thị bình quân đạt 26 m2/người; tỷ lệ nhà kiên cố toàn tỉnh đạt khoảng 70%.  + Tỷ lệ giao thông so với diện tích đất xây dựng đô thị từ 20% trở lên; tỷ lệ vận tải hành khách công cộng đáp ứng nhu cầu tại đô thị từ loại IV trở lên đạt từ 15 - 20%; các đô thị loại V đạt từ 5 - 10%.  + Tỷ lệ dân cư đô thị được cấp nước sạch tại các đô thị đạt 100%; tiêu chuẩn cấp nước cho đô thị từ loại IV trở lên đạt >120 lít/người/ngày đêm, đô thị loại V đạt >100 lít/người/ngày đêm.  + Tỷ lệ bao phủ của hệ thống thoát nước đạt 90% diện tích lưu vực thoát nước trong các đô thị và 65% lượng nước thải sinh hoạt được thu gom và xử lý; 100% các cơ sở sản xuất mới áp dụng công nghệ sạch hoặc trang bị các thiết bị giảm ô nhiễm. Các cơ sở gây ô nhiễm môi trường nghiêm trọng được xử lý đạt 90%.  + Tỷ lệ chất thải rắn sinh hoạt của đô thị, khu, cụm công nghiệp được thu gom và xử lý đạt 95%; đạt 100% chất thải rắn y tế nguy hại được thu gom và xử lý đảm bảo tiêu chuẩn môi trường.  + Tỷ lệ chiều dài các tuyến đường chính và khu nhà ở, ngõ xóm được chiếu sáng tại các đô thị loại II đạt tỷ lệ 95%; các đô thị loại III, loại IV, loại V đạt 90% chiều dài các tuyến đường chính và đạt 85% chiều dài đường khu nhà ở, ngõ xóm.  + Đất cây xanh đô thị, đối với đô thị loại II, loại III đạt 10m2/người; đô thị loại IV đạt 7m2/người; đô thị loại V đạt 3 - 4m2/người. Đất cây xanh công cộng khu vực nội thị của các đô thị từ loại II đến đô thị loại V đạt 4 - 6 m2/người.  - Đến năm 2030:  + Diện tích sàn nhà ở đô thị bình quân đạt 29m2/người; tỷ lệ nhà kiên cố toàn tỉnh đạt khoảng 75%.  + Tỷ lệ giao thông so với diện tích đất xây dựng đô thị từ 25% trở lên; tỷ lệ vận tải hành khách công cộng đáp ứng nhu cầu tại đô thị từ loại IV trở lên đạt từ 20 - 30%; các đô thị loại V đạt từ 10 - 15%.  + Tỷ lệ dân cư đô thị được cấp nước sạch tại các đô thị đạt 100%. Tiêu chuẩn cấp nước cho đô thị từ loại IV trở lên đạt >150 lít/người/ngày đêm, đô thị loại V đạt >120 lít/người/ngày đêm.  + Tỷ lệ bao phủ của hệ thống thoát nước đạt 95% diện tích lưu vực thoát nước trong các đô thị và 70% lượng nước thải sinh hoạt được thu gom và xử lý; 100% các cơ sở sản xuất mới áp dụng công nghệ sạch hoặc trang bị các thiết bị giảm ô nhiễm. Các cơ sở gây ô nhiễm môi trường nghiêm trọng được xử lý đạt 100%.  + Tỷ lệ chất thải rắn sinh hoạt của đô thị, khu, cụm công nghiệp được thu gom và xử lý đạt 100%; đạt 100% chất thải rắn y tế nguy hại được thu gom và xử lý đảm bảo tiêu chuẩn môi trường.  + Tỷ lệ chiều dài các tuyến đường chính và khu nhà ở, ngõ xóm được chiếu sáng tại các đô thị loại I đến loại II đạt tý lệ 100%; các đô thị loại III, loại IV, loại V đạt 95% chiều dài các tuyến đường chính và đạt 90% chiều dài đường khu nhà ở, ngõ xóm.  + Đất cây xanh đô thị, đối với đồ thị loại I, loại II đạt 15m2/người; đô thị loại III, loại IV đạt 10 m2/người; đồ thị loại V đạt 4 - 5m2/người. Đất cây xanh công cộng khu vực nội thị của các đô thị từ loại I đến đô thị loại V đạt 6 - 8m2/người. IV. Danh mục lộ trình nâng loại đô thị  Tập trung đầu tư xây dựng đô thị mới, gắn với việc mở rộng, nâng cấp, chỉnh trang đô thị và trung tâm cấp Vùng theo hướng văn minh, hiện đại, có bản sắc, thân thiện môi trường; hình thành và phát triển đồng bộ các đô thị là trung tâm hành chính cấp huyện; thu hút đầu tư phát triển các đô thị tiềm năng. Cụ thể phân làm 03 giai đoạn chính cần tập trung đầu tư và phát triển như sau:  - Giai đoạn từ nay đến năm 2020: Tập trung nguồn lực đầu tư phát triển, nâng cấp thành phố Cao Lãnh và thành phố Sa Đéc lên đô thị loại II, thị xã Hồng Ngự lên đô thị loại III; Hoàn thiện đầy đủ các tiêu chí đô thị loại IV còn thiếu cho thị trấn Mỹ An, thị trấn Lấp Vò và thị trấn Mỹ Thọ; cải tạo, nâng cấp thị trấn Tràm Chim (huyện Tam Nông), thị trấn Thanh Bình (huyện Thanh Bình) lên đô thị loại IV; hoàn thiện đầy đủ tiêu chí cho các đô thị loại V mới thành lập, trong đó thành lập thị trấn Thường Thới (huyện Hồng Ngự); phát triển mới 08 đô thị loại V gồm: Mỹ Hiệp (huyện Cao Lãnh), Tân Thành (huyện Lai Vung), Bình Thành (huyện Thanh Bình), An Long (huyện Tam Nông), Tân Khánh Trung, Mỹ An Hưng B (huyện Lấp Vò), Thường Phước (huyện Hồng Ngự), Dinh Bà (huyện Tân Hồng).  - Giai đoạn 2021 - 2025: Hoàn thiện đầy đủ tiêu chí đô thị loại II cho thành phố Cao Lãnh và thành phố Sa Đéc và tiêu chí đô thị loại III cho thị xã Hồng Ngự, trong đó tập trung xây dựng thành phố Cao Lãnh và thành phố Sa Đéc tiếp cận tiêu chí đô thị loại I, thị xã Hồng Ngự tiếp cận tiêu chí đô thị loại II; đầu tư xây dựng đô thị Mỹ An tiếp cận đô thị loại III, trong đó nâng cấp đô thị thị trấn Mỹ An lên thành thị xã; cải tạo, nâng cấp thị trấn Lai Vung (huyện Lai Vung), thị trấn Sa Rài (huyện Tân Hồng), thị trấn Cái Tàu Hạ - Nha Mân (huyện Châu Thành) lên đô thị loại IV; phát triển mới 04 đô thị loại V gồm: Giồng Găng (huyện Tân Hồng), An Phong (huyện Thanh Bình), Phương Trà (huyện Cao Lãnh), Phong Hòa (huyện Lai Vung).  - Giai đoạn 2026 - 2030: Nâng cấp thành phố Cao Lãnh và thành phố Sa Đéc lên đô thị loại I, thị xã Hồng Ngự lên loại II và thị xã Mỹ An lên đồ thị loại III. Phát triển mới 05 đô thị loại V gồm: Long Khánh B (huyện Hồng Ngự); Tân Thạnh, Tân Mỹ (huyện Thanh Bình); Bình Hàng Trung (huyện Cao Lãnh); Tân Dương (huyện Lai Vung). V. Chương trình dự án ưu tiên đầu tư 1. Chương trình dự án ưu tiên đầu tư phát triển hệ thống hạ tầng khung và công trình đấu mối hạ tầng kỹ thuật kết nối hệ thống đô thị  - Tập trung phát triển Khu kinh tế cửa khẩu, các trung tâm thương mại nội địa, các chợ đầu mối, chợ biên giới....Hoàn thiện và mở rộng các khu, cụm công nghiệp hiện hữu, quy hoạch và xây dựng mới các khu, cụm công nghiệp tại các đô thị trung tâm tiểu vùng.',
 'len': 2080}

In [41]:
dataset

Dataset({
    features: ['idx_merge', 'text', 'len'],
    num_rows: 135046
})

In [40]:
HfFolder.save_token('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')

dataset.push_to_hub('VTSNLP/base_vbpl_full')

Uploading the dataset shards:   0%|          | 0/4 [00:00<?, ?it/s]
Creating parquet from Arrow format:   0%|          | 0/34 [00:00<?, ?ba/s]
Creating parquet from Arrow format:  12%|█▏        | 4/34 [00:00<00:00, 30.72ba/s]
Creating parquet from Arrow format:  24%|██▎       | 8/34 [00:00<00:00, 28.90ba/s]
Creating parquet from Arrow format:  32%|███▏      | 11/34 [00:00<00:00, 26.64ba/s]
Creating parquet from Arrow format:  44%|████▍     | 15/34 [00:00<00:00, 27.37ba/s]
Creating parquet from Arrow format:  56%|█████▌    | 19/34 [00:00<00:00, 29.15ba/s]
Creating parquet from Arrow format:  65%|██████▍   | 22/34 [00:00<00:00, 28.86ba/s]
Creating parquet from Arrow format:  74%|███████▎  | 25/34 [00:00<00:00, 28.30ba/s]
Creating parquet from Arrow format:  85%|████████▌ | 29/34 [00:01<00:00, 29.64ba/s]
Creating parquet from Arrow format: 100%|██████████| 34/34 [00:01<00:00, 28.16ba/s]
Uploading the dataset shards:  25%|██▌       | 1/4 [00:06<00:20,  6.71s/it]
Creating parquet from Arrow format:   0%|          | 0/34 [00:00<?, ?ba/s]
Creating parquet from Arrow format:  12%|█▏        | 4/34 [00:00<00:00, 32.00ba/s]
Creating parquet from Arrow format:  24%|██▎       | 8/34 [00:00<00:00, 33.46ba/s]
Creating parquet from Arrow format:  35%|███▌      | 12/34 [00:00<00:00, 33.13ba/s]
Creating parquet from Arrow format:  47%|████▋     | 16/34 [00:00<00:00, 32.90ba/s]
Creating parquet from Arrow format:  59%|█████▉    | 20/34 [00:00<00:00, 31.16ba/s]
Creating parquet from Arrow format:  71%|███████   | 24/34 [00:00<00:00, 29.59ba/s]
Creating parquet from Arrow format:  82%|████████▏ | 28/34 [00:00<00:00, 30.05ba/s]
Creating parquet from Arrow format: 100%|██████████| 34/34 [00:01<00:00, 30.74ba/s]
Uploading the dataset shards:  50%|█████     | 2/4 [00:12<00:12,  6.21s/it]
Creating parquet from Arrow format:   0%|          | 0/34 [00:00<?, ?ba/s]
Creating parquet from Arrow format:  12%|█▏        | 4/34 [00:00<00:00, 30.60ba/s]
Creating parquet from Arrow format:  24%|██▎       | 8/34 [00:00<00:00, 30.10ba/s]
Creating parquet from Arrow format:  35%|███▌      | 12/34 [00:00<00:00, 29.90ba/s]
Creating parquet from Arrow format:  47%|████▋     | 16/34 [00:00<00:00, 31.48ba/s]
Creating parquet from Arrow format:  59%|█████▉    | 20/34 [00:00<00:00, 32.04ba/s]
Creating parquet from Arrow format:  71%|███████   | 24/34 [00:00<00:00, 31.07ba/s]
Creating parquet from Arrow format:  82%|████████▏ | 28/34 [00:00<00:00, 32.51ba/s]
Creating parquet from Arrow format: 100%|██████████| 34/34 [00:01<00:00, 32.15ba/s]
Uploading the dataset shards:  75%|███████▌  | 3/4 [00:17<00:05,  5.80s/it]
Creating parquet from Arrow format:   0%|          | 0/34 [00:00<?, ?ba/s]
Creating parquet from Arrow format:   9%|▉         | 3/34 [00:00<00:01, 22.26ba/s]
Creating parquet from Arrow format:  18%|█▊        | 6/34 [00:00<00:01, 22.97ba/s]
Creating parquet from Arrow format:  26%|██▋       | 9/34 [00:00<00:01, 21.44ba/s]
Creating parquet from Arrow format:  35%|███▌      | 12/34 [00:00<00:01, 21.79ba/s]
Creating parquet from Arrow format:  44%|████▍     | 15/34 [00:00<00:00, 23.59ba/s]
Creating parquet from Arrow format:  53%|█████▎    | 18/34 [00:00<00:00, 24.77ba/s]
Creating parquet from Arrow format:  62%|██████▏   | 21/34 [00:00<00:00, 25.50ba/s]
Creating parquet from Arrow format:  71%|███████   | 24/34 [00:01<00:00, 24.87ba/s]
Creating parquet from Arrow format:  79%|███████▉  | 27/34 [00:01<00:00, 25.81ba/s]
Creating parquet from Arrow format:  91%|█████████ | 31/34 [00:01<00:00, 27.73ba/s]
Creating parquet from Arrow format: 100%|██████████| 34/34 [00:01<00:00, 25.18ba/s]
Uploading the dataset shards: 100%|██████████| 4/4 [00:24<00:00,  6.04s/it]

CommitInfo(commit_url='https://huggingface.co/datasets/VTSNLP/base_vbpl_full/commit/cc8ca69c800cc19954f9031325afd8e319e97baa', commit_message='Upload dataset', commit_description='', oid='cc8ca69c800cc19954f9031325afd8e319e97baa', pr_url=None, pr_revision=None, pr_num=None)

In [8]:
# dataset = load_dataset("TeeA/VinAIResearch-ViText2SQL", token=HF_TOKEN["TeeA"], name="syllable-level")
# dataset = dataset["train"].train_test_split(test_size=TEST_SIZE, shuffle=False)
dataset = load_dataset("TeeA/text2sql_vi-2", token=HF_TOKEN["TeeA"], name="CoT")
dataset = dataset["train"].train_test_split(test_size=200, shuffle=False)

In [9]:
dataset

DatasetDict({
    train: Dataset({
        features: ['schema_syll', 'schema_word', 'query_syll', 'source', 'question_syll', 'question_word', 'query_word', 'gemini_response', 'gemini_response_vi', 'query_word_tokens', 'query_syll_tokens'],
        num_rows: 66593
    })
    test: Dataset({
        features: ['schema_syll', 'schema_word', 'query_syll', 'source', 'question_syll', 'question_word', 'query_word', 'gemini_response', 'gemini_response_vi', 'query_word_tokens', 'query_syll_tokens'],
        num_rows: 200
    })
})

In [10]:
dataset['train'] = dataset['train'].map(lambda example : {'dataset' : 'train'})
dataset['test'] = dataset['test'].map(lambda example : {'dataset' : 'test'})

Map: 100%|██████████| 66593/66593 [00:07<00:00, 8878.36 examples/s]
Map: 100%|██████████| 200/200 [00:00<00:00, 8986.77 examples/s]

In [11]:
from datasets import concatenate_datasets, load_dataset

dataset1 = concatenate_datasets([dataset['train'],dataset['test']])

In [12]:
dataset1

Dataset({
    features: ['schema_syll', 'schema_word', 'query_syll', 'source', 'question_syll', 'question_word', 'query_word', 'gemini_response', 'gemini_response_vi', 'query_word_tokens', 'query_syll_tokens', 'dataset'],
    num_rows: 66793
})

In [13]:
import re
from string import punctuation
from copy import deepcopy

sql_list_keyword = list(set(
    [
        "order",
        "view",
        "select",
        "from",
        "group",
        "exists",
        "index",
        "drop",
        "top",
        "set",
        "values",
        "union",
        "unique",
        "top",
        "or",
        "limit",
        "like",
        "where",
        "not",
        "join",
        "from",
        "desc",
        "default",
        "database",
        "delete",
        "distinct",
        "check",
        "case",
        "alter",
        "any",
        "all",
        "add",
        "asc",
        "as",
        "in",
        "table",
        "returning",
        "return",
    ] +
    [
        "ABORT", "ACTION", "ADD", "AFTER", "ALL", "ALTER", "ANALYZE", "AND", "AS", "ASC",
        "ATTACH", "AUTOINCREMENT", "BEFORE", "BEGIN", "BETWEEN", "BY", "CASCADE", "CASE", "CAST",
        "CHECK", "COLLATE", "COLUMN", "COMMIT", "CONFLICT", "CONSTRAINT", "CREATE", "CROSS", "CURRENT",
        "CURRENT_DATE", "CURRENT_TIME", "CURRENT_TIMESTAMP", "DATABASE", "DEFAULT", "DEFERRABLE",
        "DEFERRED", "DELETE", "DESC", "DETACH", "DISTINCT", "DO", "DROP", "EACH", "ELSE", "END",
        "ESCAPE", "EXCEPT", "EXCLUSIVE", "EXISTS", "EXPLAIN", "FAIL", "FILTER", "FIRST", "FOLLOWING",
        "FOR", "FOREIGN", "FROM", "FULL", "GLOB", "GROUP", "GROUPS", "HAVING", "IF", "IGNORE", "IMMEDIATE",
        "IN", "INDEX", "INDEXED", "INITIALLY", "INNER", "INSERT", "INSTEAD", "INTERSECT", "INTO", "IS",
        "ISNULL", "JOIN", "KEY", "LAST", "LEFT", "LIKE", "LIMIT", "MATCH", "NATURAL", "NO", "NOT", "NOTNULL",
        "NULL", "NULLS", "OF", "OFFSET", "ON", "OR", "ORDER", "OUTER", "OVER", "PARTITION", "PLAN", "PRAGMA",
        "PRECEDING", "PRIMARY", "QUERY", "RAISE", "RANGE", "RECURSIVE", "REFERENCES", "REGEXP", "REINDEX",
        "RELEASE", "RENAME", "REPLACE", "RESTRICT", "RIGHT", "ROLLBACK", "ROW", "ROWS", "SAVEPOINT", "SELECT",
        "SET", "TABLE", "TEMP", "TEMPORARY", "THEN", "TIES", "TO", "TRANSACTION", "TRIGGER", "UNBOUNDED",
        "UNION", "UNIQUE", "UPDATE", "USING", "VACUUM", "VALUES", "VIEW", "VIRTUAL", "WHEN", "WHERE", "WINDOW",
        "WITH", "WITHOUT"
    ] +
    ['AVG', 'COUNT', 'FIRST', 'GROUP_CONCAT', 'LAST', 'MAX', 'MIN', 'STD', 'SUM', 'TOTAL', 'VAR', 'COALESCE', 'IIF', 'SUBSTR', 'TRIM']
    + ['INTEGER','INT','SMALLINT','TINYINT','BIGINT','FLOAT','DECIMAL','NUMERIC','REAL','DOUBLE','DATE','TIME','DATETIME','TIMESTAMP','BOOLEAN','BLOB','CLOB','TEXT','CHAR','VARCHAR','NCHAR','NVARCHAR','NUMBER']
))

#sql_list_keyword = [ele.lower() for ele in sql_list_keyword] + [ele.upper() for ele in sql_list_keyword]
sql_list_keyword = [ele.lower() for ele in sql_list_keyword]

In [14]:
sql_dict_keyword = list(set(sql_list_keyword))
sql_dict_keyword = {ele : i for i,ele in enumerate(sql_dict_keyword)}

In [15]:
query_syll = dataset1['query_syll']

In [16]:
query_syll[3]

'SELECT Trụ sở chính, AVG (Nhà sản xuất) FROM Sản phẩm AS T1 JOIN Nhà sản xuất AS T2 ON T1.Nhà sản xuất = T2.Mã GROUP BY Trụ sở chính ORDER BY Trụ sở chính'

In [17]:
vectorizer = TfidfVectorizer(vocabulary=sql_dict_keyword, sublinear_tf=True, use_idf=True)

vectorizer.fit(query_syll)

# Transform text data to get TF-IDF matrix (embeddings)
tfidf_matrix = vectorizer.transform(query_syll)

# Access embeddings (each row represents a document, each column represents a word)
print(tfidf_matrix.toarray())  # Print TF-IDF weights as a NumPy array

# Alternatively, access vocabulary list
print(vectorizer.get_feature_names_out())  # Print vocabulary words

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
['all' 'without' 'exists' 'cascade' 'left' 'notnull' 'constraint' 'outer'
 'is' 'update' 'rename' 'integer' 'unique' 'in' 'escape' 'delete'
 'boolean' 'before' 'on' 'varchar' 'ties' 'row' 'each' 'or' 'if' 'column'
 'savepoint' 'nulls' 'window' 'primary' 'real' 'sum' 'into' 'view'
 'rollback' 'select' 'fail' 'reindex' 'conflict' 'drop' 'union' 'indexed'
 'like' 'std' 'from' 'preceding' 'unbounded' 'group' 'any' 'over' 'then'
 'attach' 'current_time' 'distinct' 'order' 'trigger' 'text'
 'autoincrement' 'glob' 'replace' 'insert' 'when' 'exclusive' 'first'
 'deferrable' 'restrict' 'nvarchar' 'rows' 'raise' 'database' 'smallint'
 'query' 'instead' 'join' 'explain' 'number' 'action' 'references' 'else'
 'not' 'with' 'except' 'inner' 'table' 'filter' 'max' 'as' 'timestamp'
 'between' 'analyze' 'detach' 'natural' 'release' 'avg' 'desc' 'range'
 'full' 'using' 'top' 'match' 'nchar' 'vacuum' 'commit' 'values'
 'datetime' 'after' 'add' 'partition' 'group_concat' 'total' 'index'
 'abort' 'count' 'plan' 'default' 'return' 'limit' 'transaction' 'for'
 'current' 'coalesce' 'check' 'double' 'decimal' 'begin' 'create' 'ignore'
 'isnull' 'initially' 'trim' 'cast' 'date' 'to' 'asc' 'clob' 'virtual'
 'float' 'null' 'current_date' 'key' 'alter' 'substr' 'set' 'groups'
 'intersect' 'regexp' 'having' 'case' 'var' 'of' 'tinyint' 'iif'
 'recursive' 'where' 'following' 'time' 'bigint' 'do' 'foreign' 'numeric'
 'no' 'pragma' 'int' 'deferred' 'temporary' 'returning' 'right' 'end' 'by'
 'last' 'cross' 'and' 'char' 'temp' 'min' 'offset' 'blob'
 'current_timestamp' 'collate' 'immediate']

In [18]:
tfidf_array = tfidf_matrix.toarray()

In [19]:
from sklearn.cluster import KMeans

In [21]:
import numpy as np
import pandas as pd
import datetime
import matplotlib
import matplotlib.pyplot as plt
from matplotlib import colors
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA
from sklearn.cluster import KMeans, AgglomerativeClustering
import matplotlib.pyplot as plt, numpy as np
from matplotlib import cm
from sklearn.metrics import silhouette_samples, silhouette_score

from sklearn.mixture import GaussianMixture

import warnings
warnings.filterwarnings("ignore")
from tqdm import tqdm

def inertia_plot(clust, X, start = 2, stop = 13):
    inertia = []
    for x in tqdm(range(start,stop)):
        km = clust(n_clusters = x)
        labels = km.fit_predict(X)
        inertia.append(km.inertia_)
    plt.figure(figsize = (12,6))
    plt.plot(range(start,stop), inertia, marker = 'o')
    plt.xlabel('Number of Clusters')
    plt.ylabel('Inertia')
    plt.title('Inertia plot with K')
    plt.xticks(list(range(start, stop)))
    plt.show()

In [ ]:
inertia_plot(KMeans, tfidf_array)

  0%|          | 0/11 [00:00<?, ?it/s]