In [1]:
!nvidia-smi

Tue Apr 23 03:26:50 2024
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 530.30.02              Driver Version: 530.30.02    CUDA Version: 12.1     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                  Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf            Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  NVIDIA A100-SXM4-80GB           Off| 00000000:07:00.0 Off |                    0 |
| N/A   62C    P0              107W / 400W|  79963MiB / 81920MiB |    100%      Default |
|                                         |                      |             Disabled |
+-----------------------------------------+----------------------+----------------------+
|   1  NVIDIA A100-SXM4-80GB           Off| 00000000:0F:00.0 Off |                    0 |
| N/A   70C    P0              397W / 400W|  64379MiB / 81920MiB |    100%      Default |
|                                         |                      |             Disabled |
+-----------------------------------------+----------------------+----------------------+
|   2  NVIDIA A100-SXM4-80GB           Off| 00000000:47:00.0 Off |                    0 |
| N/A   66C    P0              309W / 400W|  53915MiB / 81920MiB |    100%      Default |
|                                         |                      |             Disabled |
+-----------------------------------------+----------------------+----------------------+
|   3  NVIDIA A100-SXM4-80GB           Off| 00000000:4E:00.0 Off |                    0 |
| N/A   66C    P0              397W / 400W|  52225MiB / 81920MiB |    100%      Default |
|                                         |                      |             Disabled |
+-----------------------------------------+----------------------+----------------------+
|   4  NVIDIA A100-SXM4-80GB           Off| 00000000:87:00.0 Off |                    0 |
| N/A   49C    P0               76W / 400W|   2007MiB / 81920MiB |      0%      Default |
|                                         |                      |             Disabled |
+-----------------------------------------+----------------------+----------------------+
|   5  NVIDIA A100-SXM4-80GB           Off| 00000000:90:00.0 Off |                    0 |
| N/A   49C    P0               70W / 400W|      3MiB / 81920MiB |      0%      Default |
|                                         |                      |             Disabled |
+-----------------------------------------+----------------------+----------------------+
|   6  NVIDIA A100-SXM4-80GB           Off| 00000000:B7:00.0 Off |                    0 |
| N/A   47C    P0               66W / 400W|      3MiB / 81920MiB |      0%      Default |
|                                         |                      |             Disabled |
+-----------------------------------------+----------------------+----------------------+
|   7  NVIDIA A100-SXM4-80GB           Off| 00000000:BD:00.0 Off |                    0 |
| N/A   47C    P0               67W / 400W|      3MiB / 81920MiB |      0%      Default |
|                                         |                      |             Disabled |
+-----------------------------------------+----------------------+----------------------+

+---------------------------------------------------------------------------------------+
| Processes:                                                                            |
|  GPU   GI   CI        PID   Type   Process name                            GPU Memory |
|        ID   ID                                                             Usage      |
|=======================================================================================|
|    0   N/A  N/A   2977525      C   python                                    78634MiB |
|    0   N/A  N/A   4126647      C   ...nh/python_venv/3.10_venv/bin/python     1326MiB |
|    1   N/A  N/A   2979633      C   /usr/bin/python                           64376MiB |
|    2   N/A  N/A   2979634      C   /usr/bin/python                           53912MiB |
|    3   N/A  N/A   2979635      C   /usr/bin/python                           52222MiB |
|    4   N/A  N/A   3709912      C   python3                                    2004MiB |
+---------------------------------------------------------------------------------------+

In [2]:
from pyvi.ViTokenizer import tokenize

In [3]:
import torch
print(torch.__version__)

2.2.2+cu121

In [4]:
import os
os.environ["CUDA_DEVICE_ORDER"] = "PCI_BUS_ID"
os.environ["CUDA_VISIBLE_DEVICES"] = "4"

In [5]:
torch.cuda.device_count()

1

In [6]:
from datasets import load_dataset, Dataset, DatasetDict
import pandas as pd
import torch
import transformers
import os
import argparse
import bitsandbytes as bnb
from functools import partial
import os
from peft import LoraConfig, get_peft_model, prepare_model_for_kbit_training, AutoPeftModelForCausalLM, PeftModel
from transformers import AutoModelForCausalLM, AutoTokenizer, set_seed, Trainer, TrainingArguments, BitsAndBytesConfig, \
    DataCollatorForLanguageModeling, Trainer, TrainingArguments, BloomForCausalLM, BloomTokenizerFast, pipeline, \
    EarlyStoppingCallback
from accelerate import dispatch_model, infer_auto_device_map
from accelerate.utils import get_balanced_memory
from huggingface_hub.hf_api import HfFolder

/home/minhnh/python_venv/nlp/lib/python3.9/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
2024-04-23 03:27:56.314711: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:9261] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2024-04-23 03:27:56.314778: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:607] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2024-04-23 03:27:56.315505: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1515] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2024-04-23 03:27:56.321306: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2024-04-23 03:27:57.127742: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT

In [1]:
from huggingface_hub import login

login("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")

import datasets
import pandas as pd

/home/minhnh/python_venv/nlp/lib/python3.9/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

Token has not been saved to git credential helper. Pass `add_to_git_credential=True` if you want to set the git credential as well.
Token is valid (permission: write).
Your token has been saved to /raid/phundh/.cache/huggingface/token
Login successful

In [8]:
# dataset = datasets.load_dataset("json", data_files ="hf://datasets/MBZUAI/Bactrian-X/data/vi.json.gz")
dataset1 = datasets.load_dataset('kimnt93/viet-alpaca')
dataset2 = datasets.load_dataset('kimnt93/viet-self-instruct-gpt3.5')
dataset3 = datasets.load_dataset('kimnt93/viet-laion-c2')
dataset4 = datasets.load_dataset('kimnt93/vietdish')

In [9]:
dataset1

DatasetDict({
    train: Dataset({
        features: ['instruction', 'input', 'output'],
        num_rows: 50905
    })
})

In [51]:
dataset2

DatasetDict({
    train: Dataset({
        features: ['instruction', 'input', 'output'],
        num_rows: 34153
    })
})

In [53]:
dataset4

DatasetDict({
    train: Dataset({
        features: ['instruction', 'input', 'output'],
        num_rows: 6652
    })
})

In [56]:
dataset4['train']["instruction"][0]

'Cho biết cách làm sữa chua tự nhiên từ sữa tươi và men sữa chua.'

In [10]:
df1 = pd.DataFrame(dataset1['train'])
df2 = pd.DataFrame(dataset2['train'])
df3 = pd.DataFrame(dataset3['train'])
df4 = pd.DataFrame(dataset4['train'])

merged_df = pd.concat([df1, df2, df3, df4], ignore_index= True)
merged_df

,instruction,input,output
0,Công nghệ đám mây mang lại lợi ích gì cho doan...,,Công nghệ đám mây (cloud computing) mang lại m...
1,tạo mã HTML để tạo liên kết.,https://www.example.com -> https://www.example...,Đây là mã HTML để tạo liên kết:\n\n```html\n<a...
2,Chia nhóm các số sau thành số lẻ và số chẵn: 4...,,"Số chẵn: 4, 8, 6\nSố lẻ: 9, 3"
3,Tạo một giống như so sánh so sánh máy in với m...,,Máy in có thể được so sánh với một xe buýt.\n\...
4,Phiên dịch nghĩa của câu tục ngữ này.,Không phải cái nào lấp lánh cũng là vàng.,Điều này ý chỉ rằng không phải mọi thứ có vẻ n...
...,...,...,...
129888,Hãy cung cấp cho tôi một danh sách các loại th...,,Dưới đây là một danh sách các loại thực phẩm c...
129889,"Làm một món pizza từ bột, sốt cà chua và toppi...","Khi có nhiều trái cà chua tươi ngon, bạn hãy l...",Cám ơn bạn đã chia sẻ cách làm sốt cà chua. Nế...
129890,Bạn có thể chỉ cho tôi cách làm một món tráng ...,,Tất nhiên! Một món tráng miệng đơn giản và ngo...
129891,Tôi muốn một thực đơn chay cho ngày sinh nhật ...,,Chắc chắn! Dưới đây là một số gợi ý cho thực đ...
129892,Có thể bạn gợi ý một món tráng miệng không đườ...,,"Tất nhiên! Một món tráng miệng không đường, kh..."

**meaning level**

In [11]:
import torch
from transformers import AutoModel, AutoTokenizer

phobert = AutoModel.from_pretrained("vinai/phobert-base-v2", device_map = "auto")
tokenizer = AutoTokenizer.from_pretrained("vinai/phobert-base-v2")

Some weights of RobertaModel were not initialized from the model checkpoint at vinai/phobert-base-v2 and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

In [12]:
instruction_df = pd.DataFrame({"instruction": merged_df["instruction"]})

In [13]:
instruction_df["instruction"] = instruction_df["instruction"].map(tokenize)

In [14]:
instruction_df.head()

                                         instruction
0  Công_nghệ đám mây mang lại lợi_ích gì cho doan...
1                      tạo mã HTML để tạo liên_kết .
2  Chia nhóm các số sau thành số_lẻ và số_chẵn : ...
3  Tạo một giống như so_sánh so_sánh máy_in với m...
4             Phiên_dịch nghĩa của câu tục_ngữ này .

In [15]:
!ls -lh

total 64K
-rw-rw-r--+ 1 phundh phundh 37K Apr 22 11:11 clustering-Copy1.ipynb
-rw-r--r--  1 phundh phundh 23K Apr 23 03:32 clustering.ipynb

In [16]:
from tqdm import tqdm

list_emb = []
for i in tqdm(range(len(instruction_df["instruction"]))):
    input_ids = torch.tensor([tokenizer.encode(instruction_df["instruction"][i],truncation=True, max_length=254)])

    with torch.no_grad():
      features = phobert(input_ids.to('cuda:0'))
    list_emb.append((i,features))

100%|██████████| 129893/129893 [15:38<00:00, 138.42it/s]

In [17]:
import pickle

len_emb = len(list_emb)
print(len_emb)
list_emb_1 = [(i,ele[0][:, 0, :].to('cpu').numpy()) for i,ele in list_emb]
list_emb_2 = [(i,ele.squeeze(0)) for i,ele in list_emb_1]
# with open("my_array_word.pickle", "wb") as f:
#     pickle.dump(list_emb_2, f)

129893

In [18]:
import json
import numpy as np

list_data = []
for i,emb in list_emb_2:
    list_data.append({
        'index' : i,
        'emb' : emb
    })

In [30]:
df = pd.DataFrame(list_data)
from datasets import Dataset
from huggingface_hub.hf_api import HfFolder
from huggingface_hub import create_repo

HfFolder.save_token('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')
key_hf = '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'
# create_repo("VTSNLP/kimnt93_vi_embeddings", repo_type="dataset",private=True)

dataset = Dataset.from_pandas(df.reset_index(drop= True))
dataset.push_to_hub("VTSNLP/kimnt93_vi_embeddings")

Uploading the dataset shards:   0%|          | 0/1 [00:00<?, ?it/s]
Creating parquet from Arrow format:   0%|          | 0/130 [00:00<?, ?ba/s]
Creating parquet from Arrow format:   3%|▎         | 4/130 [00:00<00:03, 37.87ba/s]
Creating parquet from Arrow format:   6%|▌         | 8/130 [00:00<00:03, 36.62ba/s]
Creating parquet from Arrow format:  10%|█         | 13/130 [00:00<00:03, 38.27ba/s]
Creating parquet from Arrow format:  14%|█▍        | 18/130 [00:00<00:02, 38.95ba/s]
Creating parquet from Arrow format:  17%|█▋        | 22/130 [00:00<00:02, 38.46ba/s]
Creating parquet from Arrow format:  20%|██        | 26/130 [00:00<00:02, 38.11ba/s]
Creating parquet from Arrow format:  23%|██▎       | 30/130 [00:00<00:02, 38.59ba/s]
Creating parquet from Arrow format:  27%|██▋       | 35/130 [00:00<00:02, 38.93ba/s]
Creating parquet from Arrow format:  30%|███       | 39/130 [00:01<00:02, 38.94ba/s]
Creating parquet from Arrow format:  34%|███▍      | 44/130 [00:01<00:02, 39.81ba/s]
Creating parquet from Arrow format:  37%|███▋      | 48/130 [00:01<00:02, 39.08ba/s]
Creating parquet from Arrow format:  41%|████      | 53/130 [00:01<00:01, 39.74ba/s]
Creating parquet from Arrow format:  44%|████▍     | 57/130 [00:01<00:02, 34.09ba/s]
Creating parquet from Arrow format:  48%|████▊     | 62/130 [00:01<00:01, 36.14ba/s]
Creating parquet from Arrow format:  52%|█████▏    | 67/130 [00:01<00:01, 37.75ba/s]
Creating parquet from Arrow format:  55%|█████▌    | 72/130 [00:01<00:01, 39.03ba/s]
Creating parquet from Arrow format:  59%|█████▉    | 77/130 [00:02<00:01, 39.79ba/s]
Creating parquet from Arrow format:  63%|██████▎   | 82/130 [00:02<00:01, 38.07ba/s]
Creating parquet from Arrow format:  67%|██████▋   | 87/130 [00:02<00:01, 38.83ba/s]
Creating parquet from Arrow format:  71%|███████   | 92/130 [00:02<00:00, 39.64ba/s]
Creating parquet from Arrow format:  75%|███████▍  | 97/130 [00:02<00:00, 40.31ba/s]
Creating parquet from Arrow format:  78%|███████▊  | 102/130 [00:02<00:00, 40.65ba/s]
Creating parquet from Arrow format:  82%|████████▏ | 107/130 [00:02<00:00, 40.95ba/s]
Creating parquet from Arrow format:  86%|████████▌ | 112/130 [00:02<00:00, 40.94ba/s]
Creating parquet from Arrow format:  90%|█████████ | 117/130 [00:02<00:00, 41.25ba/s]
Creating parquet from Arrow format:  94%|█████████▍| 122/130 [00:03<00:00, 41.08ba/s]
Creating parquet from Arrow format: 100%|██████████| 130/130 [00:03<00:00, 39.30ba/s]
Uploading the dataset shards: 100%|██████████| 1/1 [00:03<00:00,  3.84s/it]

CommitInfo(commit_url='https://huggingface.co/datasets/VTSNLP/kimnt93_vi_embeddings/commit/2b8bc96b300aba04d9794d4b9eebb7fb7f7e8720', commit_message='Upload dataset', commit_description='', oid='2b8bc96b300aba04d9794d4b9eebb7fb7f7e8720', pr_url=None, pr_revision=None, pr_num=None)

In [3]:
from datasets import Dataset, load_dataset
from huggingface_hub.hf_api import HfFolder
from huggingface_hub import create_repo

HfFolder.save_token('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')
key_hf = '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'

dataset = load_dataset("VTSNLP/kimnt93_vi_embeddings")

In [4]:
dataset

DatasetDict({
    train: Dataset({
        features: ['index', 'emb'],
        num_rows: 129893
    })
})

In [6]:
df = pd.DataFrame(dataset['train'])

In [8]:
df

         index                                                emb
0            0  [0.2814382016658783, 0.4044457972049713, -0.19...
1            1  [0.09364411234855652, 0.7643531560897827, -0.4...
2            2  [-0.07411058247089386, 0.49893420934677124, -0...
3            3  [-0.006028988864272833, 0.4042004346847534, -0...
4            4  [0.028496630489826202, 0.5707323551177979, -0....
...        ...                                                ...
129888  129888  [0.32980766892433167, 0.4960525631904602, -0.2...
129889  129889  [0.15398506820201874, 0.2559283673763275, -0.5...
129890  129890  [0.31888434290885925, 0.13432973623275757, -0....
129891  129891  [0.2085120528936386, 0.3362034261226654, -0.11...
129892  129892  [0.22588716447353363, 0.1926996409893036, -0.3...

[129893 rows x 2 columns]

In [10]:
df.drop(df.columns[0], axis = 1, inplace= True)
df

                                                      emb
0       [0.2814382016658783, 0.4044457972049713, -0.19...
1       [0.09364411234855652, 0.7643531560897827, -0.4...
2       [-0.07411058247089386, 0.49893420934677124, -0...
3       [-0.006028988864272833, 0.4042004346847534, -0...
4       [0.028496630489826202, 0.5707323551177979, -0....
...                                                   ...
129888  [0.32980766892433167, 0.4960525631904602, -0.2...
129889  [0.15398506820201874, 0.2559283673763275, -0.5...
129890  [0.31888434290885925, 0.13432973623275757, -0....
129891  [0.2085120528936386, 0.3362034261226654, -0.11...
129892  [0.22588716447353363, 0.1926996409893036, -0.3...

[129893 rows x 1 columns]

In [11]:
df = df.reset_index(drop= True)

In [12]:
dataset = Dataset.from_pandas(df)
dataset.push_to_hub("VTSNLP/kimnt93_vi_embeddings")

Uploading the dataset shards:   0%|          | 0/2 [00:00<?, ?it/s]
Creating parquet from Arrow format:   0%|          | 0/65 [00:00<?, ?ba/s]
Creating parquet from Arrow format:   5%|▍         | 3/65 [00:00<00:02, 29.42ba/s]
Creating parquet from Arrow format:   9%|▉         | 6/65 [00:00<00:01, 29.56ba/s]
Creating parquet from Arrow format:  15%|█▌        | 10/65 [00:00<00:01, 29.95ba/s]
Creating parquet from Arrow format:  20%|██        | 13/65 [00:00<00:01, 29.71ba/s]
Creating parquet from Arrow format:  26%|██▌       | 17/65 [00:00<00:01, 25.54ba/s]
Creating parquet from Arrow format:  32%|███▏      | 21/65 [00:00<00:01, 27.21ba/s]
Creating parquet from Arrow format:  38%|███▊      | 25/65 [00:00<00:01, 28.38ba/s]
Creating parquet from Arrow format:  43%|████▎     | 28/65 [00:00<00:01, 28.71ba/s]
Creating parquet from Arrow format:  49%|████▉     | 32/65 [00:01<00:01, 29.43ba/s]
Creating parquet from Arrow format:  54%|█████▍    | 35/65 [00:01<00:01, 29.44ba/s]
Creating parquet from Arrow format:  60%|██████    | 39/65 [00:01<00:00, 29.88ba/s]
Creating parquet from Arrow format:  65%|██████▍   | 42/65 [00:01<00:00, 29.76ba/s]
Creating parquet from Arrow format:  71%|███████   | 46/65 [00:01<00:00, 29.76ba/s]
Creating parquet from Arrow format:  77%|███████▋  | 50/65 [00:01<00:00, 30.03ba/s]
Creating parquet from Arrow format:  83%|████████▎ | 54/65 [00:01<00:00, 29.90ba/s]
Creating parquet from Arrow format:  89%|████████▉ | 58/65 [00:01<00:00, 30.07ba/s]
Creating parquet from Arrow format: 100%|██████████| 65/65 [00:02<00:00, 29.40ba/s]
Uploading the dataset shards:  50%|█████     | 1/2 [00:13<00:13, 13.89s/it]
Creating parquet from Arrow format:   0%|          | 0/65 [00:00<?, ?ba/s]
Creating parquet from Arrow format:   5%|▍         | 3/65 [00:00<00:02, 26.45ba/s]
Creating parquet from Arrow format:   9%|▉         | 6/65 [00:00<00:02, 27.21ba/s]
Creating parquet from Arrow format:  14%|█▍        | 9/65 [00:00<00:02, 27.47ba/s]
Creating parquet from Arrow format:  18%|█▊        | 12/65 [00:00<00:01, 27.65ba/s]
Creating parquet from Arrow format:  23%|██▎       | 15/65 [00:00<00:01, 27.86ba/s]
Creating parquet from Arrow format:  28%|██▊       | 18/65 [00:00<00:01, 28.16ba/s]
Creating parquet from Arrow format:  32%|███▏      | 21/65 [00:00<00:01, 28.15ba/s]
Creating parquet from Arrow format:  37%|███▋      | 24/65 [00:00<00:01, 28.21ba/s]
Creating parquet from Arrow format:  42%|████▏     | 27/65 [00:00<00:01, 28.40ba/s]
Creating parquet from Arrow format:  46%|████▌     | 30/65 [00:01<00:01, 28.30ba/s]
Creating parquet from Arrow format:  51%|█████     | 33/65 [00:01<00:01, 28.32ba/s]
Creating parquet from Arrow format:  55%|█████▌    | 36/65 [00:01<00:01, 28.39ba/s]
Creating parquet from Arrow format:  60%|██████    | 39/65 [00:01<00:00, 28.43ba/s]
Creating parquet from Arrow format:  65%|██████▍   | 42/65 [00:01<00:00, 28.11ba/s]
Creating parquet from Arrow format:  69%|██████▉   | 45/65 [00:01<00:00, 27.39ba/s]
Creating parquet from Arrow format:  74%|███████▍  | 48/65 [00:01<00:00, 27.83ba/s]
Creating parquet from Arrow format:  78%|███████▊  | 51/65 [00:01<00:00, 28.09ba/s]
Creating parquet from Arrow format:  83%|████████▎ | 54/65 [00:01<00:00, 27.66ba/s]
Creating parquet from Arrow format:  88%|████████▊ | 57/65 [00:02<00:00, 27.26ba/s]
Creating parquet from Arrow format:  92%|█████████▏| 60/65 [00:02<00:00, 27.58ba/s]
Creating parquet from Arrow format: 100%|██████████| 65/65 [00:02<00:00, 27.86ba/s]
Uploading the dataset shards: 100%|██████████| 2/2 [00:25<00:00, 12.75s/it]

CommitInfo(commit_url='https://huggingface.co/datasets/VTSNLP/kimnt93_vi_embeddings/commit/e3c7accbaa75d927ce9cd0afeddb21fbeb5de983', commit_message='Upload dataset', commit_description='', oid='e3c7accbaa75d927ce9cd0afeddb21fbeb5de983', pr_url=None, pr_revision=None, pr_num=None)

In [13]:
dataset = load_dataset("VTSNLP/kimnt93_vi_embeddings")
dataset

Downloading readme: 100%|██████████| 285/285 [00:00<00:00, 2.36MB/s]
Downloading data: 100%|██████████| 326M/326M [00:06<00:00, 53.5MB/s]
Downloading data: 100%|██████████| 326M/326M [00:06<00:00, 49.4MB/s]
Generating train split: 100%|██████████| 129893/129893 [00:02<00:00, 48796.54 examples/s]

DatasetDict({
    train: Dataset({
        features: ['emb'],
        num_rows: 129893
    })
})